### ISSUE TITLE
TabBar 页签的居中显示问题

### ISSUE THREAD

**Issue by nclight** [tinper-bee/bee-tabs#2]
我希望圈中的页签头 能否居中显示  能否提供一下例子
![selection_017](https://user-images.githubusercontent.com/32626678/32262967-8f19d814-bf12-11e7-8e44-914284818d35.png)

下面是我的代码
![selection_018](https://user-images.githubusercontent.com/32626678/32262993-b6209196-bf12-11e7-971a-06358a1aeb56.png)

**Comment by BoyuZhou** [comment]
你这个地方的业务，其实不适合使用tab，可以使用纯html，使用state控制显示隐藏，来达到业务效果
