### ISSUE TITLE
竖向tab点选第一个问题

### ISSUE THREAD

**Issue by tankjun** [tinper-bee/bee-tabs#3]
竖向demo 点选第一个Tabpane，把所有的key =2,3,4 全部都显示到第一个了，

**Comment by BoyuZhou** [comment]
你使用的是哪个版本？

**Comment by tankjun** [comment]
1.0.5 这个和样式有关系吗？是不是我得吧tabs.css引入进来

**Comment by BoyuZhou** [comment]
可是试着给tabs设置高度；
![image](https://user-images.githubusercontent.com/14073759/32646642-6ad22bec-c628-11e7-8a62-60e63a829129.png)

**Comment by tankjun** [comment]
现在有个这个问题就是我的竖向tab里面嵌套了一个横向tab 竖向的样式影响了里面的横向，横向的高也是9999，导致里面横向tab 拉长了
![qq 20171110152253](https://user-images.githubusercontent.com/32053876/32647222-2abf9622-c62b-11e7-84fe-9b6603c6d84d.png)

**Comment by tankjun** [comment]
![qq 20171110152715](https://user-images.githubusercontent.com/32053876/32647274-5228b158-c62b-11e7-9b25-b7d7ad87fb0a.png)

**Comment by BoyuZhou** [comment]
我们之前没有考虑到tab嵌套的问题，现在提供给你两个暂时解决方案，1、左侧不写成tab，写成列表加路由切换。2、对里面的tab通过传入className，或style进行样式复写。
这个问题，我们也会尽快修复的。

**Comment by tankjun** [comment]
恩，好的，知道了，谢谢
